version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: racecraft_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/racecraft_dev
      REDIS_URL: redis://redis:6379
      # add other env vars as needed
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis

volumes:
  pgdata:
